# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
      - image: lamdencalrissian/seneca-myrocks-test:0.6
        environment:
          username: seneca_test
          password: ci_bad_pw
          database: seneca_test
    working_directory: ~/src/lamden/seneca

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt install -y mysql-client
            sudo apt install -y python-mysqldb
            sudo pip install -r requirements.txt
            sudo pip install -r dev-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: set temp credentials file
          command: |
             ./scripts/make_test_config.py --password ci_bad_pw --hostname 127.0.0.1

      - run:
          name: Wait For mysqld
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: run tests
          command: |
            make test

      - run:
          name: run coverage
          command: |
            make coverage

  test-cilantro:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/src/lamden/seneca

    steps:
      - checkout
      - run:
          name: Test Cilantro
          command: |
            echo "Testing Cilantro using Seneca Branch {{ .Branch }}"
            python3 scripts/cilantro_ci.py --seneca_branch {{ .Branch }}


workflows:
  version: 2
  build_and_test_cilantro:
    jobs:
      - build
      - test-cilantro
